sudo: false
language: java
jdk:
  - oraclejdk8
  - oraclejdk9
  - openjdk10
  - openjdk9
  - openjdk8

script: mvn clean verify

after_success:
  - bash <(curl -s https://codecov.io/bash) -t e1c3b44e-c681-4a3a-a1ff-bbaf340b5661
